---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: gitops-foundations
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/maayanyosef/gitops-foundations-env-2892009.git
